const links = [
    // Root to cats
    { source: 'root', target: 'cat-orka', label: 'POV 1', type: 'cat' },
    { source: 'root', target: 'cat-varg', label: 'POV 2', type: 'cat' },
    { source: 'root', target: 'cat-elvar', label: 'POV 3', type: 'cat' },
    { source: 'root', target: 'cat-mundo', label: 'mundo', type: 'cat' },
    { source: 'root', target: 'cat-tramas', label: 'tramas', type: 'cat' },
    { source: 'root', target: 'cat-facciones', label: 'poder', type: 'cat' },
    { source: 'root', target: 'cat-eventos', label: '', type: 'arc' },
    { source: 'root', target: 'cat-norse', label: 'cultura', type: 'cat' },
    // -------------------------------------------------------------------------------------- //
    // Cat-orka to orka chars
    // Orka
    { source: 'orka', target: 'cat-orka', label: '', type: 'arc' },
    { source: 'orka', target: 'thorkel', label: 'Esposo', type: 'rel' },
    { source: 'orka', target: 'breca', label: 'Hijo', type: 'rel' },
    { source: 'orka', target: 'asgrim-death', label: 'descubre', type: 'event' },
    { source: 'orka', target: 'spert', label: 'vínculo sangre', type: 'magic' },
    { source: 'orka', target: 'virk', label: 'comercian', type: 'event' },
    { source: 'orka', target: 'sigrun', label: 'la cuestiona en el Althing', type: 'event' },
    { source: 'orka', target: 'thrall-sigrun', label: 'observa lamiendo sangre de Thorkel', type: 'event' },
    { source: 'orka', target: 'second-combat', label: 'segundo de Virk', type: 'event' },
    { source: 'orka', target: 'karl', label: 'vive como', type: 'rel' },
    { source: 'orka', target: 'froa', label: 'encontro muerta', type: 'event' },
    { source: 'orka', target: 'barrow-virk', label: 'ayudo a construir', type: 'event' },
    { source: 'orka', target: 'decision-huida', label: 'propone huir', type: 'event' },
    // Thorkel
    { source: 'thorkel', target: 'virk', label: 'comercian', type: 'history' },
    { source: 'thorkel', target: 'breca', label: 'Hijo', type: 'rel' },
    { source: 'thorkel', target: 'asgrim-death', label: 'descubre', type: 'event' },
    { source: 'thorkel', target: 'thrall-sigrun', label: 'pateó / identificó Ulfrir-kin', type: 'event' },
    { source: 'thorkel', target: 'drengr', label: 'se considera', type: 'rel' },
    { source: 'thorkel', target: 'thrall', label: 'ex-thrall', type: 'rel' },
    { source: 'thorkel', target: 'karl', label: 'vive como', type: 'rel' },
    { source: 'thorkel', target: 'ulfhednar', label: 'identifica el tipo', type: 'trama' },
    { source: 'thorkel', target: 'decision-huida', label: 'acepta sin resistencia', type: 'event' },
    { source: 'thorkel', target: 'colgante-espada', label: 'tallo para Breca', type: 'rel' },
    // Breca
    { source: 'breca', target: 'vesli', label: 'protege / jura', type: 'magic' },
    { source: 'breca', target: 'hueso-dios-fellur', label: 'reacción', type: 'trama' },
    { source: 'breca', target: 'asgrim-death', label: 'descubre', type: 'event' },
    { source: 'breca', target: 'tainted', label: 'posible sangre', type: 'trama' },
    // Gudvarr
    { source: 'gudvarr', target: 'sigrun', label: 'sobrino', type: 'rel' },
    { source: 'gudvarr', target: 'niding', label: 'insultó a Virk', type: 'event' },
    // Arild
    { source: 'arild', target: 'sigrun', label: 'Drengr de', type: 'rel' },
    { source: 'arild', target: 'gudvarr', label: 'acompaña a', type: 'rel' },
    { source: 'arild', target: 'second-combat', label: 'segundo de Guðvarr', type: 'event' },
    // Virk
    { source: 'virk', target: 'mord-lif', label: 'hijos', type: 'trama' },
    { source: 'virk', target: 'funeral-rites', label: 'cuerpo envuelto', type: 'event' },
    { source: 'virk', target: 'holmganga-event', label: 'combatiente', type: 'rel' },
    // Thrall de Sigrun
    { source: 'thrall-sigrun', target: 'sigrun', label: 'sirve a / guardaespaldas', type: 'rel' },
    { source: 'thrall-sigrun', target: 'tainted', label: '¿sangre divina?', type: 'trama' },
    { source: 'thrall-sigrun', target: 'ulfrir', label: 'sangre confirmada', type: 'rel' },
    { source: 'thrall-sigrun', target: 'seax', label: 'usa dos', type: 'rel' },
    // Asgrim
    { source: 'asgrim', target: 'idrun', label: 'esposo/a', type: 'rel' },
    { source: 'asgrim', target: 'asgrim-death', label: 'muerto en', type: 'event' },
    { source: 'asgrim', target: 'harek', label: 'padre', type: 'rel' },
    // Idrun
    { source: 'idrun', target: 'harek', label: 'madre', type: 'rel' },
    { source: 'idrun', target: 'asgrim-death', label: 'muerta en', type: 'event' },
    // Sigrun
    { source: 'sigrun', target: 'fellur', label: 'jarl de', type: 'arc' },
    { source: 'sigrun', target: 'helka', label: 'juro lealtad', type: 'rel' },
    { source: 'sigrun', target: 'althing', label: 'anunció juramento', type: 'event' },
    { source: 'sigrun', target: 'brynja', label: 'lleva remachada', type: 'rel' },
    // Falki
    { source: 'falki', target: 'oath-stone-fellur', label: 'asiste Althing', type: 'event' },
    // Vesli
    { source: 'vesli', target: 'tennur', label: 'Es un', type: 'lore' },
    // Spert
    { source: 'spert', target: 'spertus', label: 'Es un', type: 'lore' },
    // Spert
    { source: 'helka', target: 'cat-facciones', label: '', type: 'arc' },
    { source: 'helka', target: 'darl', label: 'sede', type: 'geo' },
    { source: 'helka', target: 'orna', label: 'huesos en fortaleza', type: 'lore' },
    // -------------------------------------------------------------------------------------- //
    // Cat-varg to varg chars
    // Varg
    { source: 'varg', target: 'cat-varg', label: '', type: 'arc' },
    { source: 'varg', target: 'froya', label: 'hermana', type: 'rel' },
    { source: 'varg', target: 'leif', label: 'enemigo', type: 'conflict' },
    { source: 'varg', target: 'liga', label: 'visita', type: 'geo' },
    { source: 'varg', target: 'svik', label: 'compañero', type: 'rel' },
    { source: 'varg', target: 'sulich', label: 'lo reconoce sin saber', type: 'trama' },
    { source: 'varg', target: 'vol', label: 'la busca para akáll', type: 'goal' },
    { source: 'varg', target: 'bloodsworn', label: 'nuevo miembro', type: 'event' },
    { source: 'varg', target: 'akall', label: 'necesita', type: 'goal' },
    { source: 'varg', target: 'tainted', label: 'posible sangre', type: 'trama' },
    { source: 'varg', target: 'thrall', label: 'ex-thrall', type: 'rel' },
    { source: 'varg', target: 'varg-aprendiz', label: 'definido como', type: 'rel' },
    { source: 'varg', target: 'partida-liga', label: 'zarpa en', type: 'event' },
    { source: 'varg', target: 'objeto-viga', label: 'nota pero no pregunta', type: 'trama' },
    // bloodsworn
    { source: 'bloodsworn', target: 'cat-varg', label: '', type: 'arc' },
    { source: 'bloodsworn', target: 'cat-facciones', label: '', type: 'arc' },
    { source: 'bloodsworn', target: 'glornir', label: 'jefe', type: 'rel' },
    { source: 'bloodsworn', target: 'liga', label: 'base en', type: 'geo' },
    // Rokia
    { source: 'rokia', target: 'varg', label: 'entrena', type: 'goal' },
    { source: 'rokia', target: 'bloodsworn', label: 'miembro', type: 'rel' },
    // Guerrero Oscuro
    { source: 'sulich', target: 'glornir', label: 'sparring / misterio', type: 'trama' },
    { source: 'sulich', target: 'bloodsworn', label: 'miembro', type: 'rel' },
    // Edel
    { source: 'edel', target: 'cat-varg', label: '', type: 'arc' },
    { source: 'edel', target: 'bloodsworn', label: 'escoutmaestre', type: 'rel' },
    // Einar
    { source: 'einar', target: 'bloodsworn', label: 'miembro', type: 'rel' },
    { source: 'snepil', target: 'cat-varg', label: '', type: 'arc' },
    // Svik
    { source: 'svik', target: 'bloodsworn', label: 'miembro', type: 'rel' },
    { source: 'svik', target: 'varg-aprendiz', label: 'guia al aprendiz', type: 'rel' },
    // Vol
    { source: 'vol', target: 'bloodsworn', label: 'miembro / thrall', type: 'rel' },
    { source: 'vol', target: 'seidr', label: 'practica', type: 'magic' },
    { source: 'vol', target: 'thrall', label: 'thrall', type: 'rel' },
    { source: 'vol', target: 'akall', label: 'dispuesta pero bloqueada', type: 'goal' },
    { source: 'vol', target: 'partida-liga', label: 'zarpa con Hermanos', type: 'event' },
    // Glornir
    { source: 'glornir', target: 'bloodsworn', label: 'jefe', type: 'rel' },
    { source: 'glornir', target: 'varg-aprendiz', label: 'define condiciones', type: 'rel' },
    { source: 'glornir', target: 'partida-liga', label: 'ordena', type: 'event' },
    // Snepil
    { source: 'einar', target: 'varg', label: 'enfrenta por puesto', type: 'event' },
    { source: 'snepil', target: 'varg', label: 'fue su amo', type: 'rel' },
    { source: 'snepil', target: 'leif', label: 'padre', type: 'rel' },
    { source: 'snepil', target: 'orl', label: 'thrall de confianza', type: 'rel' },
    // Torvik
    { source: 'torvik', target: 'cat-varg', label: '', type: 'arc' },
    { source: 'torvik', target: 'bloodsworn', label: 'aspirante', type: 'rel' },
    { source: 'torvik', target: 'edel', label: 'scout bajo mando de', type: 'rel' },
    { source: 'torvik', target: 'jokul', label: 'aprendiz de', type: 'rel' },
    { source: 'torvik', target: 'varg', label: 'compañero aspirante', type: 'rel' },
    // Galinn
    { source: 'galinn', target: 'liga', label: 'skáld de', type: 'geo' },
    { source: 'galinn', target: 'gudfall-saga-galinn', label: 'recita', type: 'event' },
    { source: 'galinn', target: 'cat-varg', label: '', type: 'arc' },
    { source: 'galinn', target: 'skald', label: 'Es un', type: 'lore' },
    // Sergei
    { source: 'sergei', target: 'cat-facciones', label: '', type: 'arc' },
    { source: 'sergei', target: 'jaromir', label: 'herald de', type: 'rel' },
    { source: 'sergei', target: 'jarl-logur', label: 'viejo amigo', type: 'rel' },
    { source: 'sergei', target: 'iskidan', label: 'mercader de', type: 'geo' },
    { source: 'sergei', target: 'sulich-crisis', label: 'mediador', type: 'event' },
    // Jaromir
    { source: 'jaromir', target: 'cat-facciones', label: '', type: 'arc' },
    { source: 'jaromir', target: 'emp-kirill', label: 'hijo del', type: 'rel' },
    { source: 'jaromir', target: 'sulich-crisis', label: 'protagoniza', type: 'event' },
    { source: 'jaromir', target: 'sulich', label: 'exige por crímenes', type: 'conflict' },
    { source: 'jaromir', target: 'glornir', label: 'confrontación', type: 'conflict' },
    { source: 'jaromir', target: 'jarl-logur', label: 'visita / ultimátum', type: 'event' },
    { source: 'jaromir', target: 'ilia', label: 'druzhina', type: 'rel' },
    { source: 'jaromir', target: 'druzhina', label: 'escoltado por', type: 'rel' },
    // Ilia
    { source: 'ilia', target: 'jaromir', label: 'druzhina de', type: 'rel' },
    { source: 'ilia', target: 'druzhina', label: 'es', type: 'lore' },
    { source: 'ilia', target: 'sulich-crisis', label: 'dispuesta a matar', type: 'event' },
    // -------------------------------------------------------------------------------------- //
    // Cat-elvar to elvar chars
    // Elvar
    { source: 'elvar', target: 'cat-elvar', label: '', type: 'arc' },
    { source: 'elvar', target: 'grend', label: 'guardián', type: 'rel' },
    { source: 'elvar', target: 'biorr', label: 'tensión', type: 'trama' },
    { source: 'elvar', target: 'battle-grim', label: 'miembro', type: 'rel' },
    { source: 'elvar', target: 'oath-stone-frost-isles', label: 'presenció activación', type: 'event' },
    { source: 'elvar', target: 'dragon-born', label: 'niega existencia', type: 'conflict' },
    // Agnar
    { source: 'agnar', target: 'sighvat', label: 'jefe/subof.', type: 'rel' },
    { source: 'agnar', target: 'iskalt', label: 'asaltó buscando a Berak', type: 'geo' },
    { source: 'agnar', target: 'jarl-hrut', label: 'Mató a Jarl Hrut durante el asalto a Iskalt', type: 'event' },
    { source: 'agnar', target: 'battle-grim', label: 'jefe', type: 'rel' },
    { source: 'agnar', target: 'oath-stone-frost-isles', label: 'presenció / reflexionó', type: 'event' },
    { source: 'agnar', target: 'dragon-born', label: 'esperaría encontrar', type: 'trama' },
    // Berak
    { source: 'berak', target: 'uspa', label: 'esposo', type: 'rel' },
    { source: 'berak', target: 'bjarn', label: 'padre', type: 'rel' },
    { source: 'berak', target: 'berser', label: 'sangre y herencia confirmada', type: 'lore' },
    { source: 'berak', target: 'tainted', label: 'Berserkir', type: 'lore' },
    // battle Grim
    { source: 'battle-grim', target: 'cat-facciones', label: '', type: 'arc' },
    { source: 'battle-grim', target: 'cat-elvar', label: '', type: 'arc' },
    { source: 'battle-grim', target: 'berak', label: 'Buscado y capturado', type: 'event' },
    { source: 'battle-grim', target: 'wave-jarl', label: 'Navio', type: 'rel' },
    { source: 'battle-grim', target: 'sjavarom', label: 'Pelearon contra', type: 'Evento' },
    // grend
    { source: 'grend', target: 'battle-grim', label: 'miembro', type: 'rel' },
    // Uspa mujer Berak
    { source: 'uspa', target: 'sjavarom', label: 'controló', type: 'magic' },
    { source: 'uspa', target: 'seidr', label: 'practica', type: 'magic' },
    { source: 'uspa', target: 'snaka', label: 'sangre y herencia confirmada', type: 'lore' },
    { source: 'uspa', target: 'tainted', label: 'sangre Snaka', type: 'lore' },
    { source: 'uspa', target: 'oath-stone-frost-isles', label: 'activa con sangre', type: 'magic' },
    { source: 'uspa', target: 'gudfall', label: 'explica causa', type: 'lore' },
    { source: 'uspa', target: 'bjarn', label: 'madre de Bjarn', type: 'rel' },
    { source: 'uspa', target: 'dragon-born', label: 'escupitajo sospechoso', type: 'trama' },
    // Hijo-berak (Bjarn)
    { source: 'bjarn', target: 'berak', label: 'hijo de', type: 'rel' },
    { source: 'bjarn', target: 'snaka', label: 'sangre (por Uspa)', type: 'lore' },
    { source: 'bjarn', target: 'berser', label: 'sangre (por Berak)', type: 'lore' },
    { source: 'bjarn', target: 'tainted', label: 'doble linaje divino', type: 'lore' },
    // Sighvat
    { source: 'sighvat', target: 'kraka', label: 'controla', type: 'rel' },
    { source: 'sighvat', target: 'hundur', label: 'controla', type: 'rel' },
    // kraka
    { source: 'kraka', target: 'battle-grim', label: 'miembro/thrall', type: 'rel' },
    { source: 'kraka', target: 'wave-jarl', label: 'protege con Seiðr', type: 'magic' },
    { source: 'kraka', target: 'seidr', label: 'practica', type: 'magic' },
    { source: 'kraka', target: 'tainted', label: 'Tainted', type: 'lore' },
    { source: 'kraka', target: 'thrall', label: 'thrall', type: 'rel' },
    { source: 'kraka', target: 'oath-stone-frost-isles', label: 'identificó / reconoció', type: 'magic' },
    // hundur (thrall)
    { source: 'hundur', target: 'battle-grim', label: 'miembro/thrall', type: 'rel' },
    { source: 'hundur', target: 'berak', label: 'rastreó', type: 'event' },
    { source: 'hundur', target: 'hundur-dios', label: 'sangre de', type: 'lore' },
    { source: 'hundur', target: 'oath-stone-frost-isles', label: 'detectó con olfato', type: 'event' },
    // biorr
    { source: 'biorr', target: 'battle-grim', label: 'miembro', type: 'rel' },
    // storr
    { source: 'storr', target: 'cat-facciones', label: '', type: 'arc' },
    { source: 'storr', target: 'snakavik', label: 'sede', type: 'geo' },
    { source: 'storr', target: 'berak', label: 'comprador', type: 'trama' },
    // -------------------------------------------------------------------------------------- //
    // Lenguajes
    { source: 'galdur', target: 'galdur', label: '', type: 'arc' },
    { source: 'galdur', target: 'cat-magia', label: 'Lenguaje Magico', type: 'arc' },
    { source: 'galdur', target: 'collares', label: 'activa', type: 'magic' },
    // -------------------------------------------------------------------------------------- //
    // Cat-mundo
    { source: 'tainted', target: 'cat-mundo', label: '', type: 'arc' },
    // -------------------------------------------------------------------------------------- //
    // Cat-eventos
    { source: 'asgrim-death', target: 'cat-eventos', label: '', type: 'event' },
    // holmganga virk vs gudvarr
    { source: 'holmganga-event', target: 'cat-eventos', label: '', type: 'event' },
    { source: 'holmganga-event', target: 'gudvarr', label: 'combatiente', type: 'rel' },
    { source: 'holmganga-event', target: 'orka', label: 'segundo de Virk', type: 'rel' },
    { source: 'holmganga-event', target: 'thrall-sigrun', label: 'mató a Virk', type: 'event' },
    { source: 'holmganga-event', target: 'arild', label: 'segundo de Guðvarr', type: 'rel' },
    { source: 'holmganga-event', target: 'mord-lif', label: 'presenciaron', type: 'event' },
    { source: 'holmganga-event', target: 'oath-stone-fellur', label: 'lugar', type: 'geo' },
    // gudfall
    { source: 'gudfall', target: 'cat-eventos', label: '', type: 'history' },
    { source: 'gudfall', target: 'snaka', label: 'murió en', type: 'history' },
    { source: 'gudfall', target: 'orna', label: 'murió en', type: 'history' },
    { source: 'gudfall', target: 'berser', label: 'murió en', type: 'history' },
    { source: 'gudfall', target: 'likrafa', label: 'encadenada', type: 'history' },
    // -------------------------------------------------------------------------------------- //
    // Cat-dioses
    { source: 'cat-dioses', target: 'cat-mundo', label: '', type: 'arc' },
    { source: 'snaka', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'snaka', target: 'vigrið', label: 'sus huesos = montañas', type: 'lore' },
    { source: 'likrafa', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'likrafa', target: 'vergelmir', label: 'encadenada en oskutred', type: 'lore' },
    { source: 'orna', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'ulfrir', target: 'cat-dioses', label: '', type: 'lore' },
    // Svin
    { source: 'svin', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'svin', target: 'gudfall', label: 'combatió en', type: 'history' },
    // Tosk
    { source: 'tosk', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'tosk', target: 'gudfall', label: 'combatió en', type: 'history' },
    // Rotta
    { source: 'rotta', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'rotta', target: 'gudfall', label: 'combatió en', type: 'history' },
    { source: 'rotta', target: 'likrafa', label: 'alimentó su paranoia', type: 'history' },
    { source: 'rotta', target: 'gallows-wood', label: 'detonante indirecto', type: 'history' },
    // Hundur
    { source: 'hundur-dios', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'hundur-dios', target: 'gudfall', label: 'combatió en', type: 'history' },
    { source: 'hundur-dios', target: 'hundur', label: 'fuente del linaje', type: 'lore' },
    // -------------------------------------------------------------------------------------- //
    // Cat-magia
    { source: 'cat-magia', target: 'cat-mundo', label: '', type: 'arc' },
    { source: 'runa-ward', target: 'cat-magia', label: '', type: 'arc' },
    { source: 'seidr', target: 'cat-magia', label: '', type: 'arc' },
    { source: 'seidr', target: 'akall', label: 'técnica', type: 'magic' },
    { source: 'galdramadr', target: 'cat-magia', label: '', type: 'arc' },
    // -------------------------------------------------------------------------------------- //
    // Lugares
    // vigrið
    { source: 'vigrið', target: 'cat-mundo', label: '', type: 'arc' },
    // iskalt
    { source: 'iskalt', target: 'vigrið', label: 'isla en', type: 'geo' },
    { source: 'iskalt', target: 'oskutred', label: 'terremotos = Lik-Rifa', type: 'magic' },
    // snakavik
    { source: 'snakavik', target: 'vigrið', label: 'ciudad en', type: 'geo' },
    // darl
    { source: 'darl', target: 'vigrið', label: 'capital', type: 'geo' },
    // howbyr
    { source: 'howbyr', target: 'vigrið', label: 'villa en', type: 'geo' },
    // kergarth
    { source: 'kergarth', target: 'vigrið', label: 'villa en', type: 'geo' },
    // svelgarth
    { source: 'svelgarth', target: 'vigrið', label: 'ciudad en', type: 'geo' },
    // skarpain
    { source: 'rio-skarpain', target: 'vigrið', label: 'río en', type: 'geo' },
    // islas hielo
    { source: 'islas-hielo', target: 'vigrið', label: 'islas al norte', type: 'geo' },
    { source: 'islas-hielo', target: 'iskalt', label: 'al sur de', type: 'geo' },
    { source: 'islas-hielo', target: 'araña-hielo', label: 'hábitat', type: 'lore' },
    // fellur
    { source: 'fellur', target: 'vigrið', label: 'ciudad en', type: 'geo' },
    { source: 'fellur', target: 'oath-stone-fellur', label: 'isla en el fiordo', type: 'geo' },
    // liga
    { source: 'liga', target: 'vigrið', label: 'ciudad en', type: 'geo' },
    // vergelmir
    { source: 'vergelmir', target: 'oskutred', label: 'bajo él', type: 'lore' },
    // iskidan
    { source: 'iskidan', target: 'cat-mundo', label: 'capital', type: 'geo' },
    { source: 'gravka', target: 'iskidan', label: 'capital', type: 'geo' },
    // oath-stone-fellur
    { source: 'oath-stone-fellur', target: 'althing', label: 'lugar', type: 'geo' },
    // Frost-Isles
    { source: 'frost-isles', target: 'vigrið', label: 'archipiélago en', type: 'geo' },
    { source: 'frost-isles', target: 'iskalt', label: 'al sur de', type: 'geo' },
    { source: 'frost-isles', target: 'berak-venta', label: 'escala del viaje', type: 'geo' },
    // Eldrafell
    { source: 'eldrafell', target: 'vigrið', label: 'montaña en', type: 'geo' },
    { source: 'eldrafell', target: 'snaka', label: 'lugar de caída', type: 'lore' },
    { source: 'eldrafell', target: 'gudfall-saga-galinn', label: 'mencionado en', type: 'lore' },
    // -------------------------------------------------------------------------------------- //
    // Vaesen y magia
    { source: 'vaesen-gen', target: 'cat-mundo', label: '', type: 'arc' },
    { source: 'tennur', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'spertus', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'fell-wolf', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'trol', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'sjavarom', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'nacken', target: 'vaesen-gen', label: 'vaesen agua', type: 'lore' },
    { source: 'nacken', target: 'rio-skarpain', label: 'posible hábitat', type: 'lore' },
    { source: 'araña-hielo', target: 'vaesen-gen', label: 'Es un vaesen ártico', type: 'lore' },
    { source: 'skraeling', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'faunir', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'froa', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'froa', target: 'arbol-froa', label: 'ligada a / murio con', type: 'lore' },
    { source: 'froa', target: 'oskutred', label: 'nacida de semilla de', type: 'lore' },
    { source: 'froa', target: 'orka', label: 'conocidas -- Orka buscaba consejo', type: 'rel' },
    { source: 'froa', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'froa', target: 'ninos-robados', label: 'destruida por mismos agresores?', type: 'trama' },
    // Night-wyrm
    { source: 'night-wyrm', target: 'vaesen-gen', label: 'Es un', type: 'lore' },
    { source: 'night-wyrm', target: 'berak-venta', label: 'atacó en', type: 'event' },
    { source: 'night-wyrm', target: 'oath-stone-frost-isles', label: 'posiblemente atraídos por', type: 'trama' },
    { source: 'night-wyrm', target: 'biorr', label: 'repelidos con fuego por', type: 'event' },
    // -------------------------------------------------------------------------------------- //
    // Tramas
    { source: 'akall', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'ninos-robados', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'ninos-robados', target: 'harek', label: 'primer caso', type: 'trama' },
    { source: 'ninos-robados', target: 'asgrim-death', label: 'conecta con', type: 'trama' },
    { source: 'ninos-robados', target: 'orka', label: 'investiga', type: 'trama' },
    { source: 'ninos-robados', target: 'haraldurson', label: 'víctima', type: 'trama' },
    { source: 'ninos-robados', target: 'kergarth', label: 'caso en', type: 'geo' },
    { source: 'ninos-robados', target: 'howbyr', label: 'caso en', type: 'geo' },
    { source: 'ninos-robados', target: 'rio-skarpain', label: 'ruta de huida', type: 'geo' },
    { source: 'ninos-robados', target: 'asgrim', label: 'víctimas', type: 'trama' },
    // Berak-venta-event
    { source: 'berak-venta', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'berak-venta', target: 'berak', label: 'Sera vendido', type: 'trama' },
    { source: 'berak-venta', target: 'snakavik', label: 'destino', type: 'geo' },
    { source: 'berak-venta', target: 'cat-eventos', label: '', type: 'event' },
    { source: 'berak-venta', target: 'wave-jarl', label: 'navegado en', type: 'rel' },
    { source: 'berak-venta', target: 'snakavik', label: 'destino', type: 'geo' },
    { source: 'helka-poder', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'helka-poder', target: 'helka', label: 'protagoniza', type: 'trama' },
    { source: 'helka-poder', target: 'sigrun', label: 'juró lealtad', type: 'event' },
    { source: 'lik-rifa-amenaza', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'lik-rifa-amenaza', target: 'likrafa', label: 'es ella', type: 'trama' },
    { source: 'lik-rifa-amenaza', target: 'iskalt', label: 'epicentro', type: 'geo' },
    // -------------------------------------------------------------------------------------- //
    // ── ENLACES PERSONAJES SECUNDARIOS ────────────────────────────
    { source: 'jarl-logur', target: 'liga', label: 'jarl de', type: 'geo' },
    { source: 'jarl-logur', target: 'bloodsworn', label: 'hospeda', type: 'rel' },
    // Esposa de Logur
    { source: 'salla', target: 'jarl-logur', label: 'esposa de', type: 'rel' },
    { source: 'salla', target: 'liga', label: 'señora del hall de', type: 'geo' },
    { source: 'salla', target: 'partida-liga', label: 'organiza la despedida', type: 'event' },
    { source: 'salla', target: 'glornir', label: 'Glornir la llama Salla', type: 'rel' },
    { source: 'orl', target: 'leif', label: 'Hird / compañero', type: 'rel' },
    { source: 'trud', target: 'battle-grim', label: 'miembro', type: 'rel' },
    { source: 'jokul', target: 'bloodsworn', label: 'herrero', type: 'rel' },
    { source: 'jokul', target: 'einar', label: 'forjó protección', type: 'rel' },
    { source: 'jarl-hrut', target: 'iskalt', label: 'jarl de (†)', type: 'geo' },
    { source: 'slyda', target: 'liga', label: 'guarda puerta', type: 'rel' },
    { source: 'slyda', target: 'varg', label: 'dejó pasar', type: 'event' },
    { source: 'jarl-orlyg', target: 'svelgarth', label: 'jarl de', type: 'geo' },
    { source: 'haraldurson', target: 'howbyr', label: 'viven en', type: 'geo' },
    { source: 'emp-kirill', target: 'gravka', label: 'gobierna desde', type: 'geo' },
    // -------------------------------------------------------------------------------------- //
    // ── ENLACES OBJETOS ────────────────────────────────────────────
    { source: 'cat-objetos', target: 'cat-mundo', label: '', type: 'arc' },
    { source: 'collares', target: 'cat-objetos', label: '', type: 'rel' },
    { source: 'collares', target: 'cat-magia', label: '', type: 'arc' },
    { source: 'collares', target: 'tainted', label: 'controla', type: 'magic' },
    { source: 'hueso-dios-fellur', target: 'cat-objetos', label: 'protege', type: 'magic' },
    { source: 'colmillo-trol', target: 'cat-objetos', label: '', type: 'rel' },
    { source: 'colmillo-trol', target: 'elvar', label: 'otorgado a', type: 'rel' },
    { source: 'colmillo-trol', target: 'agnar', label: 'otorga', type: 'rel' },
    { source: 'colmillo-trol', target: 'trol', label: 'origen', type: 'lore' },
    { source: 'anillo-oro', target: 'elvar', label: 'otorgado a', type: 'rel' },
    { source: 'gods-bones', target: 'cat-magia', label: '', type: 'arc' },
    { source: 'hueso-dios-fellur', target: 'fellur', label: 'protege', type: 'magic' },
    { source: 'hueso-dios-fellur', target: 'gods-bones', label: 'Es un', type: 'rel' },
    { source: 'drakkar', target: 'cat-objetos', label: '', type: 'arc' },
    { source: 'drakkar', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'seax', target: 'cat-objetos', label: '', type: 'arc' },
    { source: 'seax', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'brynja', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'brynja', target: 'cat-objetos', label: '', type: 'arc' },
    // Colgante espada Breca
    { source: 'colgante-espada', target: 'breca', label: 'lo lleva', type: 'rel' },
    { source: 'colgante-espada', target: 'thorkel', label: 'lo tallo', type: 'rel' },
    { source: 'colgante-espada', target: 'cat-objetos', label: '', type: 'arc' },
    // Vackna
    { source: 'vackna', target: 'cat-dioses', label: '', type: 'arc' },
    { source: 'vackna', target: 'gudfall', label: 'inició la batalla', type: 'lore' },
    { source: 'vackna', target: 'gudfall-saga-galinn', label: 'mencionado en', type: 'lore' },
    // Arbol-Froa
    { source: 'arbol-froa', target: 'cat-orka', label: '', type: 'arc' },
    { source: 'arbol-froa', target: 'ninos-robados', label: 'destruido por mismos agresores?', type: 'trama' },
    { source: 'arbol-froa', target: 'decision-huida', label: 'hallazgo rompe el plan', type: 'event' },
    // Objeto en la viga
    { source: 'objeto-viga', target: 'cat-objetos', label: '', type: 'arc' },
    { source: 'objeto-viga', target: 'liga', label: 'ubicado en hall de', type: 'geo' },
    { source: 'objeto-viga', target: 'varg', label: 'lo nota sin entender', type: 'trama' },
    { source: 'objeto-viga', target: 'gods-bones', label: 'posible reliquia', type: 'trama' },
    // -------------------------------------------------------------------------------------- //
    // ── ENLACES CULTURA NÓRDICA ────────────────────────────────────
    { source: 'holmganga', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'holmganga', target: 'second-combat', label: 'rol en duelo', type: 'lore' },
    { source: 'holmgang-rules', target: 'holmganga', label: 'reglas del', type: 'lore' },
    { source: 'holmgang-rules', target: 'virk', label: 'violó reglas', type: 'event' },
    { source: 'holmgang-rules', target: 'gudvarr', label: 'se rindió legalmente', type: 'event' },
    { source: 'holmgang-rules', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'althing', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'niding', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'drengr', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'thrall', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'karl', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'jarl', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'blood-oath', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'wyrd', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'warrior-braid', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'skald', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'knarr', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'karvi', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'faering', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'snekkja', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'skuta', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'byrding', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'skjoldr', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'spjot', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'langsoex', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'ox', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'bogi', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'hjalmar', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'torc', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'armring', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'hird', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'skjaldborg', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'funeral-rites', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'guest-right', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'hird-offering', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'weregild', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'outlawry', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'gachas', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'mead-hall', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'steading', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'kennings', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'patronymics', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'berserkergang', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'second-combat', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'drengr', target: 'gudvarr', label: 'se considera', type: 'rel' },
    { source: 'thrall', target: 'tainted', label: 'esclavizados', type: 'lore' },
    { source: 'jarl', target: 'sigrun', label: 'es', type: 'rel' },
    { source: 'jarl', target: 'storr', label: 'es', type: 'rel' },
    { source: 'jarl', target: 'jarl-logur', label: 'es', type: 'rel' },
    { source: 'blood-oath', target: 'breca', label: 'juramento con Vesli', type: 'magic' },
    { source: 'blood-oath', target: 'sigrun', label: 'juró a Helka', type: 'event' },
    { source: 'warrior-braid', target: 'agnar', label: 'lleva', type: 'rel' },
    { source: 'warrior-braid', target: 'elvar', label: 'lleva', type: 'rel' },
    { source: 'warrior-braid', target: 'sulich', label: 'lleva', type: 'rel' },
    { source: 'wyrd', target: 'vergelmir', label: 'destino tras muerte', type: 'lore' },
    { source: 'drakkar', target: 'wave-jarl', label: 'Wave-Jarl es un drakkar', type: 'rel' },
    { source: 'drakkar', target: 'bloodsworn', label: 'tienen uno', type: 'rel' },
    { source: 'faering', target: 'virk', label: 'probablemente tenía', type: 'rel' },
    { source: 'faering', target: 'rio-skarpain', label: 'huyeron en barcas', type: 'trama' },
    { source: 'faering', target: 'fellur', label: 'villa pesquera', type: 'geo' },
    { source: 'snekkja', target: 'ninos-robados', label: 'posible embarcación raptores', type: 'trama' },
    { source: 'knarr', target: 'liga', label: 'comercio', type: 'geo' },
    { source: 'seax', target: 'thorkel', label: 'usa ritualmente', type: 'rel' },
    { source: 'seax', target: 'virk', label: 'asesinado con', type: 'event' },
    { source: 'seax', target: 'nacken', label: 'ritual protección', type: 'magic' },
    { source: 'seax', target: 'karl', label: 'símbolo hombre libre', type: 'lore' },
    { source: 'brynja', target: 'agnar', label: 'probablemente lleva', type: 'rel' },
    { source: 'skjoldr', target: 'varg', label: 'entrena con', type: 'rel' },
    { source: 'skjoldr', target: 'rokia', label: 'entrena a Varg', type: 'rel' },
    { source: 'skjoldr', target: 'bloodsworn', label: 'escudo negro', type: 'rel' },
    { source: 'skjoldr', target: 'battle-grim', label: 'escudo rojo', type: 'rel' },
    { source: 'skjoldr', target: 'elvar', label: 'escudo rojo', type: 'rel' },
    { source: 'skjoldr', target: 'jarl-logur', label: 'escudo azul', type: 'rel' },
    { source: 'spjot', target: 'leif', label: 'hirió a Varg', type: 'event' },
    { source: 'spjot', target: 'varg', label: 'herido por', type: 'event' },
    { source: 'langsoex', target: 'gudvarr', label: 'lleva al cinto', type: 'rel' },
    { source: 'langsoex', target: 'svik', label: 'lleva', type: 'rel' },
    { source: 'langsoex', target: 'sulich', label: 'espada curva', type: 'rel' },
    { source: 'ox', target: 'thorkel', label: 'hacha larga barbada', type: 'rel' },
    { source: 'ox', target: 'virk', label: 'usó en holmganga', type: 'event' },
    { source: 'ox', target: 'glornir', label: 'long-axe', type: 'rel' },
    { source: 'ox', target: 'gudvarr', label: 'herido por', type: 'event' },
    { source: 'destral', target: 'thorkel', label: 'arma principal', type: 'rel' },
    { source: 'destral', target: 'virk', label: 'usó en holmganga', type: 'event' },
    { source: 'bogi', target: 'trud', label: 'herida por flecha', type: 'event' },
    { source: 'torc', target: 'sigrun', label: 'lleva plata', type: 'rel' },
    { source: 'torc', target: 'svik', label: 'lleva plata con serpientes', type: 'rel' },
    { source: 'torc', target: 'agnar', label: 'lleva plata', type: 'rel' },
    { source: 'armring', target: 'sigrun', label: 'lleva en brazos', type: 'rel' },
    { source: 'armring', target: 'svik', label: 'lleva plata enrollados', type: 'rel' },
    { source: 'armring', target: 'glornir', label: 'Dador-de-Oro', type: 'rel' },
    { source: 'armring', target: 'bloodsworn', label: 'sistema lealtad', type: 'lore' },
    { source: 'hird', target: 'orl', label: 'Hird de Leif', type: 'rel' },
    { source: 'hird', target: 'leif', label: 'tiene Hird', type: 'rel' },
    { source: 'hird-offering', target: 'orka', label: 'advierte en Althing', type: 'event' },
    { source: 'hird-offering', target: 'helka', label: 'exigirá', type: 'trama' },
    { source: 'hird-offering', target: 'sigrun', label: 'deberá proporcionar', type: 'trama' },
    { source: 'skjaldborg', target: 'elvar', label: 'ganó puesto en muro', type: 'rel' },
    { source: 'skjaldborg', target: 'varg', label: 'entrena para', type: 'rel' },
    { source: 'skjaldborg', target: 'rokia', label: 'entrena a Varg', type: 'rel' },
    { source: 'skjaldborg', target: 'skjoldr', label: 'usa escudos', type: 'lore' },
    { source: 'funeral-rites', target: 'vergelmir', label: 'razón de armas', type: 'lore' },
    { source: 'funeral-rites', target: 'mord-lif', label: 'envuelven a padre', type: 'event' },
    { source: 'funeral-rites', target: 'thorkel', label: 'ayuda con cuerpo', type: 'event' },
    { source: 'guest-right', target: 'jarl-logur', label: 'hospeda Hermanos', type: 'rel' },
    { source: 'guest-right', target: 'bloodsworn', label: 'hospedados', type: 'rel' },
    { source: 'guest-right', target: 'agnar', label: 'ofrece comida a prisioneros', type: 'rel' },
    { source: 'weregild', target: 'mord-lif', label: 'no reciben', type: 'trama' },
    { source: 'weregild', target: 'virk', label: 'muerte sin compensación', type: 'event' },
    { source: 'outlawry', target: 'varg', label: 'proscrito de facto', type: 'trama' },
    { source: 'outlawry', target: 'snepil', label: 'asesinato causa', type: 'event' },
    { source: 'gachas', target: 'grend', label: 'sirve a Elvar', type: 'event' },
    { source: 'gachas', target: 'elvar', label: 'recibe de Grend', type: 'event' },
    { source: 'gachas', target: 'biorr', label: 'ofrece a prisioneros', type: 'event' },
    { source: 'mead-hall', target: 'jarl-logur', label: 'sala en Liga', type: 'geo' },
    { source: 'mead-hall', target: 'fellur', label: 'longhouse central', type: 'geo' },
    { source: 'mead-hall', target: 'sigrun', label: 'gobierna desde', type: 'rel' },
    { source: 'steading', target: 'orka', label: 'vive en', type: 'geo' },
    { source: 'steading', target: 'thorkel', label: 'vive en', type: 'geo' },
    { source: 'steading', target: 'asgrim', label: 'murió en su', type: 'event' },
    { source: 'kennings', target: 'glornir', label: 'Rompe-Escudos, Dador-de-Oro', type: 'rel' },
    { source: 'kennings', target: 'einar', label: 'Medio-Trol', type: 'rel' },
    { source: 'kennings', target: 'svik', label: 'Pelo-Enredado', type: 'rel' },
    { source: 'patronymics', target: 'thorkel', label: 'Ulfsson', type: 'rel' },
    { source: 'patronymics', target: 'berak', label: 'Bjornasson', type: 'rel' },
    { source: 'patronymics', target: 'leif', label: 'Kolskeggson', type: 'rel' },
    { source: 'berserkergang', target: 'berak', label: 'entra en', type: 'rel' },
    { source: 'berserkergang', target: 'varg', label: 'furia roja similar', type: 'trama' },
    { source: 'berserkergang', target: 'thrall-sigrun', label: 'furia de lobo', type: 'rel' },
    { source: 'berserkergang', target: 'berser', label: 'origen divino', type: 'lore' },
    // Blood-Eagle
    { source: 'blood-eagle', target: 'cat-norse', label: '', type: 'arc' },
    { source: 'blood-eagle', target: 'gallows-wood', label: 'imitación humana de', type: 'lore' },
    // ══════════════════════════════════════════════════════════════
    // CAPÍTULO 13 — NUEVOS ENLACES
    // ══════════════════════════════════════════════════════════════
    // Druzhina (concepto)
    { source: 'druzhina', target: 'cat-facciones', label: '', type: 'arc' },
    { source: 'druzhina', target: 'emp-kirill', label: 'guardia del', type: 'rel' },
    { source: 'druzhina', target: 'iskidan', label: 'institución de', type: 'lore' },
    // Sulich crisis
    { source: 'sulich-crisis', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'sulich-crisis', target: 'sulich', label: 'reclamado', type: 'conflict' },
    { source: 'sulich-crisis', target: 'glornir', label: 'defiende a Sulich', type: 'event' },
    { source: 'sulich-crisis', target: 'jarl-logur', label: 'árbitro potencial', type: 'rel' },
    { source: 'sulich-crisis', target: 'althing', label: 'resolución prevista', type: 'event' },
    // Saga del Gudfall (evento)
    { source: 'gudfall-saga-galinn', target: 'cat-eventos', label: '', type: 'event' },
    { source: 'gudfall-saga-galinn', target: 'gudfall', label: 'narra', type: 'lore' },
    { source: 'gudfall-saga-galinn', target: 'svin', label: 'menciona', type: 'lore' },
    { source: 'gudfall-saga-galinn', target: 'tosk', label: 'menciona', type: 'lore' },
    { source: 'gudfall-saga-galinn', target: 'rotta', label: 'menciona', type: 'lore' },
    { source: 'gudfall-saga-galinn', target: 'vackna', label: 'menciona', type: 'lore' },
    { source: 'gudfall-saga-galinn', target: 'eldrafell', label: 'menciona', type: 'lore' },
    // Relaciones nuevas de nodos ya existentes
    { source: 'sulich', target: 'sulich-crisis', label: 'centro de la crisis', type: 'conflict' },
    { source: 'sulich', target: 'iskidan', label: 'origen probable', type: 'trama' },
    { source: 'jarl-logur', target: 'salla', label: 'esposo', type: 'rel' },
    // ══════════════════════════════════════════════════════════════
    // CAPÍTULO 14 — NUEVOS ENLACES
    // ══════════════════════════════════════════════════════════════
    // Oath Stone
    { source: 'oath-stone-frost-isles', target: 'cat-objetos', label: '', type: 'arc' },
    { source: 'oath-stone-frost-isles', target: 'frost-isles', label: 'ubicada en', type: 'geo' },
    { source: 'oath-stone-frost-isles', target: 'gudfall', label: 'narra', type: 'lore' },
    { source: 'oath-stone-frost-isles', target: 'gallows-wood', label: 'muestra imagen de', type: 'lore' },
    { source: 'oath-stone-frost-isles', target: 'gods-bones', label: 'conecta con reliquias', type: 'lore' },
    // Gallows Wood
    { source: 'gallows-wood', target: 'cat-dioses', label: '', type: 'lore' },
    { source: 'gallows-wood', target: 'likrafa', label: 'crimen que lo detonó', type: 'history' },
    { source: 'gallows-wood', target: 'orna', label: 'Orna vengó a su hija', type: 'history' },
    { source: 'gallows-wood', target: 'ulfrir', label: 'Ulfrir vengó a su hija', type: 'history' },
    { source: 'gallows-wood', target: 'blood-eagle', label: 'origen del ritual', type: 'lore' },
    // Dragon-born
    { source: 'dragon-born', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'dragon-born', target: 'likrafa', label: 'posible descendencia', type: 'trama' },
    { source: 'dragon-born', target: 'tainted', label: 'linaje no confirmado', type: 'trama' },
    { source: 'dragon-born', target: 'elvar', label: 'niega su existencia', type: 'conflict' },
    { source: 'dragon-born', target: 'uspa', label: 'reacción de Uspa', type: 'trama' },
    // ==========================================================
    // CAPITULO 15 -- NUEVOS ENLACES
    // ==========================================================
    // Ulfhednar (concepto)
    { source: 'ulfhednar', target: 'thrall-sigrun', label: 'es una', type: 'lore' },
    { source: 'ulfhednar', target: 'ulfrir', label: 'linaje de', type: 'lore' },
    { source: 'ulfhednar', target: 'tainted', label: 'subtipo de', type: 'lore' },
    { source: 'ulfhednar', target: 'thorkel', label: 'conoce el termino', type: 'trama' },
    { source: 'ulfhednar', target: 'decision-huida', label: 'amenaza que motiva', type: 'trama' },
    // Decision de huida
    { source: 'decision-huida', label: '', target: 'cat-tramas', type: 'arc' },
    { source: 'decision-huida', target: 'orka', label: 'propone', type: 'event' },
    { source: 'decision-huida', target: 'thorkel', label: 'acepta', type: 'event' },
    { source: 'decision-huida', target: 'thrall-sigrun', label: 'motivada por amenaza de', type: 'trama' },
    { source: 'decision-huida', target: 'gritos-oeste', label: 'interrumpida por', type: 'event' },
    // Barrow de Virk
    { source: 'barrow-virk', target: 'cat-eventos', label: '', type: 'event' },
    { source: 'barrow-virk', target: 'virk', label: 'tumulo de', type: 'event' },
    { source: 'barrow-virk', target: 'mord-lif', label: 'construido por', type: 'event' },
    { source: 'barrow-virk', target: 'orka', label: 'ayudo a construir', type: 'event' },
    { source: 'barrow-virk', target: 'thorkel', label: 'ayudo a construir', type: 'event' },
    { source: 'barrow-virk', target: 'funeral-rites', label: 'practica de', type: 'lore' },
    // Gritos al oeste
    { source: 'gritos-oeste', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'gritos-oeste', target: 'orka', label: 'escucha -- steading en peligro?', type: 'event' },
    { source: 'gritos-oeste', target: 'ninos-robados', label: 'posiblemente relacionados', type: 'trama' },
    { source: 'gritos-oeste', target: 'steading', label: 'direccion del steading de Orka', type: 'geo' },
    // Mord y Lif
    { source: 'mord-lif', target: 'barrow-virk', label: 'construyeron', type: 'event' },
    // ==========================================================
    // CAPITULO 16 -- NUEVOS ENLACES
    // ==========================================================
    // Varg-aprendiz
    { source: 'varg-aprendiz', target: 'cat-tramas', label: '', type: 'arc' },
    { source: 'varg-aprendiz', target: 'varg', label: 'define estatus de', type: 'rel' },
    { source: 'varg-aprendiz', target: 'glornir', label: 'dictado por', type: 'rel' },
    { source: 'varg-aprendiz', target: 'akall', label: 'condiciona el', type: 'trama' },
    { source: 'varg-aprendiz', target: 'bloodsworn', label: 'paso previo a unirse a', type: 'rel' },
    // Partida de Liga
    { source: 'partida-liga', target: 'cat-eventos', label: '', type: 'event' },
    { source: 'partida-liga', target: 'bloodsworn', label: 'protagonista', type: 'rel' },
    { source: 'partida-liga', target: 'liga', label: 'desde', type: 'geo' },
    { source: 'partida-liga', target: 'varg', label: 'zarpa como aprendiz', type: 'event' },
    { source: 'partida-liga', target: 'sulich-crisis', label: 'sin resolver al partir', type: 'trama' },
];
