// Chapter summaries data
const chapterSummaries = [
  {
    chapter: 1,
    title: "Capítulo 1 — Orka",
    summary: "Año 297 del Friðaröld. Orka, Thorkel y su hijo Breca de diez inviernos se adentran en los bosques de pino de las colinas sobre el fiordo de Fellur para la primera caza del niño. Breca lanza su primera lanza pero falla: un fell-wolf (lobo caído) con heridas frescas irrumpe en el calvero y dispersa los renos. Thorkel prueba la sangre del animal con la lengua —un gesto significativo que revela su conexión con la naturaleza salvaje— mientras Orka narra el mito fundacional del mundo.<br><br>Sentados sobre una roca con vistas al fiordo, Thorkel relata la saga de los dioses: Snaka, el dios-serpiente primordial y padre de todos, fue derrocado por sus propios hijos (Águila, Oso, Lobo, Dragón y otros). Al caer, Snaka aplastó continentes y hundió reinos; sus huesos forman las cordilleras que divisan al norte. La catástrofe —conocida como Guðfalla, la Caída de los Dioses— abrió la fosa de los vaesen, liberando criaturas de dientes y garras al mundo. Este evento define toda la sociedad de Vigríð.<br><br>Gritos lejanos los interrumpen. Siguen el rastro del lobo herido hasta el steading de Asgrim, su vecino de las colinas.<br><br>Encuentran a Asgrim muerto de una estocada al corazón en el umbral, con runa de protección grabada en la puerta; a su esposa Idrun crucificada en el portón con el vientre abierto. Su hijo Harek —amigo de juegos de Breca— ha desaparecido.<br><br>No hay señales de vaesen: la runa protectora habría resistido a cualquier criatura menor. Las heridas son de hierro, obra de hombres."
  },
  {
    chapter: 2,
    title: "Capítulo 2 — Varg",
    summary: "Varg lleva nueve o diez días corriendo. Llega exhausto a Liga, ciudad mercado y puerto en el fiordo, con un collar de hierro que él mismo se coloca para fingir ser un thrall de un amo imaginario. En su interior guarda una bolsa de monedas Helka (de la reina Helka) y una bolsa pequeña que cuida con obsesión. Lleva el collar de thrall aunque es libre: lo usa como disfraz para pasar desapercibido.<br><br>En el mercado —lleno de mercaderes con marfil de morsa, partes de vaesen disecadas, pieles, especias— come un cuenco de estofado pagado con bronce partido. Un vendedor le informa que los <strong>Juramentados de Sangre</strong> (<em>Bloodsworn</em>), una legendaria compañía de mercenarios, están alojados en la sala de festín del Jarl Logur. Tienen una bruja Seiðr. Varg los busca porque necesita que realicen un <em>akáll</em> (invocación): quiere saber cómo murió su hermana Frøya.<br><br>En la plaza frente a la sala de festín, los Juramentados de Sangre celebran una prueba de combate para reclutar a quien ocupe el lugar de un guerrero caído. Einar Medio-Trol, el campeón, ha tumbado a decenas de candidatos. Varg conoce a Svik Hrulfsson (Pelo-Enredado), el reclutador de pelo rojo, elegante y sarcástico. También observa al jefe calvo de barba gris con una larga hacha y a la bruja Seiðr tatuada —Vol— con collar de hierro. Cuando Svik le niega acceso a Vol, Varg en un impulso desesperado dice que luchará contra Einar."
  },
  {
    chapter: 3,
    title: "Capítulo 3 — Orka",
    summary: "Orka y Breca llevan los cadáveres de Asgrim e Idrun en un carro hasta Fellur. Thorkel ha seguido las huellas de los asesinos. La llegada al pueblo está presidida por Guðvarr, sobrino de la Jarl Sigrún —ausente en la corte de la Reina Helka en Darl—. Guðvarr anuncia que la Jarl vuelve en nueve días y que en el Althing se debatirá jurar lealtad a Helka.<br><br>Cuando Orka descubre los cadáveres ante la multitud, Guðvarr intenta atribuirlo a vaesen para reforzar el argumento de la necesidad de Helka. Orka lo desmiente con lógica directa: vaesen no usan espadas, y la runa warding estaba intacta.<br><br>Guðvarr la amenaza en voz baja. Orka siente la ira cegadora hervir en su sangre y su cuerpo tiembla; solo la llegada de Thorkel y la mirada de Breca la detienen. Virk el pescador menciona que Harek no es el primer niño robado en la región.<br><br>Thorkel regresa: siguió las huellas hasta el Río Skarpain, donde tres barcas habían atracado —los asesinos huyeron por agua. Guðvarr promete investigar pero Orka sabe que no lo hará. La familia decide marcharse: <em>no es su problema.</em> Pero las palabras de Virk sobre los niños robados siembran una semilla de inquietud en Orka."
  },
  {
    chapter: 4,
    title: "Capítulo 4 — Varg",
    summary: "Varg entra al cuadrado y se enfrenta a Einar Medio-Trol sin escudo (rechaza el que le ofrece Glornir porque nunca ha usado uno). La mujer de nariz de proa —Røkia— lo anuncia sarcásticamente como Varg-Sin-Sentido. El combate es una paliza sistemática: Einar tiene protección de hierro forjada por Jökul el herrero alrededor de su entrepierna, lo que anula el único golpe certero de Varg. Sin embargo, Varg derriba brevemente a Einar con un golpe al riñón y una patada en la rodilla —momento de silencio atónito en la multitud—. Al final, Varg muerde la pantorrilla de Einar con tanta fuerza que hace sangrar al gigante, y recibe un puñetazo que lo noquea.<br><br>Varg despierta en la orilla del fiordo con la ropa limpiamente doblada. Decide que seguirá buscando una Seiðr-bruja aunque tenga que recorrer todo Vigríð o cruzar el mar hasta Iskidan. Mientras enciende una hoguera en el bosque, llegan Leif Kolskeggson (hijo de su antiguo amo) con varios hombres y una jauría. Leif quiere devolverlo a la esclavitud y amputarle la mano como castigo por el asesinato de Kolskegg. Justo cuando Varg está inmovilizado, aparecen Glornir (el calvo de barba gris, jefe de los Juramentados), Svik y Einar con los lobos de guerra. En segundos neutralizan a los hombres de Leif.<br><br>Glornir declara: <em>«Es uno de los Juramentados de Sangre, ahora.»</em><br><br>También se presenta Orl, el viejo thrall de Kolskegg, que cuida al perro quemado por la hoguera de Varg. Varg descubre que la motivación real para matar a Kolskegg fue un acceso de furia roja del que no recuerda nada, ligado a la muerte de su hermana Frøya."
  },
  {
    chapter: 5,
    title: "Capítulo 5 — Elvar",
    summary: "<strong>NUEVO POV:</strong> Elvar es la guerrera más joven de la Batalla-Fiera (<em>Battle-Grim</em>), compañía mercenaria que navega a bordo del drakkar <em>Wave-Jarl</em>. La acompaña siempre Grend, un guerrero mayor de barba gris, protector silencioso. Su jefe es Agnar, valiente y carismático, con una trenza guerrera y capote de piel de oso. El suboficial es el obeso y feroz Sighvat. A bordo viaja encadenada Kráka, la thrall Tainted que canta magia Seiðr para mantener a las serpientes marinas lejos del casco.<br><br>La Batalla-Fiera llega a la isla volcánica de Iskalt —marcada por venas de fuego en la roca— buscando a un hombre llamado <strong>Berak</strong>. Desembarcan ante la aldea de pescadores, mayoritariamente hostil. Agnar mata al Jarl Hrut cuando este se interpone. En el caos, Elvar ve a un hombre alto con capa de pieles que susurra algo a una niña, que corre a avisar a alguien.<br><br>Elvar señala a la niña a Agnar: <em>«Síguelas.»</em><br><br>Elvar y Grend entran a la aldea persiguiendo a la familia. Encuentran una choza vacía con un agujero en la pared trasera. El thrall Hundur (perro rastreador modificado con magia) verifica el olor: es él. La familia —Berak, su mujer y su hijo— huye hacia el bosque y las colinas. Agnar ordena perseguirlos."
  },
  {
    chapter: 6,
    title: "Capítulo 6 — Orka",
    summary: "Orka despierta de una pesadilla: imágenes de batalla, cuerpos cayendo, el rugido del mar y gritos de muerte tan vívidos como si los estuviera viviendo. Quiere alcanzar a Thorkel pero se contiene (<em>que duerma, por qué cargarlo con mi debilidad</em>). Detecta que Breca no está en su cama y sale al steading presa del pánico.<br><br>Despierta a <strong>Spert</strong>, el vaesen guardián del arroyo: criatura segmentada con cara casi humana, antenas, aguijón y dientes de doble fila. Spert fue capturado por Orka años atrás mediante vínculo de sangre (<em>ella alimenta su cuenco con sangre y saliva propias</em>) y protege el steading de otros vaesen. Spert no ha visto a Breca —dormía. Orka y Thorkel siguen las huellas hasta un estanque de montaña.<br><br>Encuentran a Breca acurrucado junto al agua con una <strong>tennúr</strong> herida en el regazo. Las tennúr son vaesen pequeños, bípedos, de alas membranosas, con dos filas de dientes y adicción por los dientes humanos. Breca le extrajo un diente de leche flojo y se lo ofreció, calmándola. La ha bautizado <strong>Vesli</strong> y dice que le habló. Orka le da una bofetada de miedo convertida en rabia. Thorkel contiene su brazo antes del segundo golpe. El capítulo cierra con la risa de Thorkel —momento de ternura familiar pura."
  },
  {
    chapter: 7,
    title: "Capítulo 7 — Elvar",
    summary: "La Batalla-Fiera sube al interior de la isla siguiendo el rastro del Hundur-thrall. Encuentran excrementos de trol —con huesos de ratas, un cuervo y una marta dentro— signo de territorio. Agnar envía a Elvar, Grend y Biórr como exploración avanzada. El trío llega a una meseta de roca volcánica junto a una cascada de lava fundida y un lago ardiente.<br><br>Allí encuentran a <strong>Berak</strong> luchando solo contra un toro-trol joven: enorme, con astas nacientes en el cráneo cubierto de musgo, dientes de marfil y piel escamosa. La mujer de Berak arroja al lago de lava un objeto —un pergamino o tablilla de cera— antes de que la Batalla-Fiera llegue. El trol mata a varios guerreros: uno cae al lago y se incinera, otro es empalado en las astas, una mujer es aplastada hasta la irreconocibilidad. Elvar clava su espada en la arteria femoral del trol: chorro de sangre negra, el monstruo se desploma.<br><br>Berak es inmovilizado. Agnar lo amenaza con degollar a su hijo para que muestre su naturaleza verdadera: los ojos de Berak se vuelven ambarinos, crece y sus dientes se agudizan. El collar de hierro con palabra de comando en Galdur lo detiene (<em>«Á HNÉN»</em> — de rodillas). Agnar confirma: Berak Bjornasson, cuya sangre porta la herencia del dios muerto <strong>Berser</strong>. Es un <strong>Berserkir</strong>. Agnar planea venderlo al Jarl Störr en <strong>Snakavik</strong>."
  },
  {
    chapter: 8,
    title: "Capítulo 8 — Orka",
    summary: "Escena doméstica. Orka afila su seax en los escalones del hall mientras vigila a Breca recoger huevos del gallinero con la carraca de Vesli al lado. Thorkel se sienta junto a ella. Hablan del equilibrio entre proteger a Breca y endurecerlo para el mundo; Thorkel revela que de joven llevó collar de thrall y tuvo la espalda abierta a latigazos —igual que Varg. Orka dice que ella no puede olvidar el pasado; Thorkel dice que elige cada día mirar lo que tiene en lugar de lo que perdió.<br><br>Vesli es presentada a Spert. La criatura segmentada la amenaza con vapor negro venenoso; Breca intercede. Vesli jura lealtad con sangre: <em>«Vesli jura ser fiel y verdadera al niño-Maður Breca, y a su guardián Spertus.»</em> Spert acepta. La tennúr queda vinculada al niño por deuda de sangre.<br><br>Llegan a caballo Guðvarr y dos drengr: la Jarl Sigrún ha vuelto y convoca Althing en la Roca del Juramento en seis días.<br><br>Orka y Thorkel debaten si ir: no quieren llamar la atención ausentándose. Thorkel tiene un mal presentimiento. Deciden asistir, <em>cabeza gacha y labios cosidos.</em>"
  },
  {
    chapter: 9,
    title: "Capítulo 9 — Elvar",
    summary: "Amanecer en la playa de Iskalt. Grend —que no ha dormido— sirve gachas. Discuten sobre <strong>Lik-Rifa</strong>, la diosa-dragón: Grend sostiene que no murió en el Guðfalla, sino que fue atrapada bajo Oskutreð, el Árbol de Ceniza, y sigue viva devorando almas de guerreros en su cámara subterránea (<em>Vergelmir</em>). La isla tiembla —venas de roca fundida destellan en la montaña— y Grend lo atribuye a Lik-Rifa forcejeando con sus cadenas. Elvar es escéptica.<br><br>La Batalla-Fiera carga la Wave-Jarl con prisioneros (Berak, su mujer e hijo), el trol destazado (piel, dientes, huesos, hígado, corazón, testículos —todo tiene precio de mercado), pieles, marfil de morsa y cabras. Kráka comienza su canto serpentario.<br><br>Cuando zarpan, Elvar avisa un movimiento en el agua. Una <strong>serpiente marina</strong> emerge: cabeza del tamaño de una cabaña, hileras de dientes, cuerpo sinuoso. Devora parte de una cabra, derriba el toldo y lanza al hijo de Berak por la borda.<br><br>Sin armas (las guardó en el cofre), Elvar salta al mar helado y agarra al niño. La serpiente se dirige a ellos. Grend salta también y la ataca con un cuchillo —inútil. La serpiente levanta las fauces sobre Elvar. En el último instante, la <strong>mujer de Berak</strong> canta desde el barco: la serpiente se detiene y se sumerge. Grend arrastra a Elvar y al niño de vuelta al casco. Agnar revela entonces que la mujer tiene sangre de <strong>Snaka</strong>: es una Seiðr-bruja de linaje divino. La amenaza: si usa sus poderes contra la tripulación, su hijo muere.<br><br>Agnar regala a Elvar un colmillo de trol —máxima distinción en la Batalla-Fiera. Le confirma el destino: Snakavik, Jarl Störr."
  },
  {
    chapter: 10,
    title: "Capítulo 10 — Orka",
    summary: "El Althing en la Roca del Juramento, un islote en el fiordo. El monolito de runas está destruido a martillazos: adorar a los dioses muertos es ilegal, penado con la muerte. Thorkel explica que los supervivientes del Guðfalla odiaban a los dioses por haber roto el mundo, y cazaron a los Tainted —portadores de sangre divina— como consecuencia. Virk lleva a la familia de Orka en su barca.<br><br>Jarl <strong>Sigrún</strong> aparece con una docena de drengr y una <strong>thrall-guerrera</strong>: mujer de cara cicatrizada, cabeza rapada a los lados con tatuajes, dos seaxes, ojos planos y despiadados. Sigrún anuncia que ha jurado lealtad a la <strong>Reina Helka</strong>, sellado con su propia sangre. La sala de festín de Helka en <strong>Darl</strong> está presidida por los huesos del dios muerto <strong>Orna</strong> —el dios-águila— incluyendo alas visibles.<br><br>Virk lidera la oposición en el Althing. Guðvarr, humillado ante la multitud por las burlas de Virk sobre su incompetencia en el caso de Asgrim y los niños, lanza un desafío de <strong>holmganga</strong> (duelo reglamentado). Virk acepta y pide a Orka que sea su segundo —no a sus hijos, para evitar que intenten vengarle si muere. Orka acepta a regañadientes.<br><br>Virk le revela a Orka que los robos de niños son múltiples y geográficamente dispersos: los Haraldurson de Howbyr perdieron tres hijos; una familia de Kergarth, igual. Un patrón organizado. Orka rompe el silencio ante el Althing y dice en voz alta lo que todos piensan: Helka pedirá un <em>hird-offering</em> —una leva de guerreros para su guerra particular. Los presentes reaccionan con reconocimiento sombrío."
  },
  {
    chapter: 11,
    title: "Capítulo 11 — Varg",
    summary: "Varg despierta en la sala de Jarl Logur después de seis días inconsciente. Svik está a su lado: lo cuidó durante la fiebre causada por la herida de lanza que Leif le propinó antes de huir. Lo primero que Varg hace al incorporarse es verificar su bolsita de cuero al cinturón, intacta. Svik le da queso y gachas con miel, lo primero que come bien en semanas.<br><br>Antes de que Varg pueda preguntar por Vol, aparece Røkia —la guerrera rubia que le ofreció un escudo antes del combate con Einar— con órdenes de Glornir: hay que entrenarle. Varg insiste dos veces en que necesita hablar con la bruja Seiðr; Røkia lo ignora las dos veces y solo dice que Vol no está. El entrenamiento empieza de inmediato en el patio, bajo la mirada divertida de Svik.<br><br>Røkia enseña fundamentos de escudo: separarlo del cuerpo para que una hoja que perfora la madera no llegue a la carne, bracear el antebrazo completo, nunca perder al enemigo de vista escondiéndose detrás de la tabla. Varg llega con instintos buenos —postura correcta de boxeador, rápido para aprender— pero Røkia lo corta cada vez que asume que ya terminó. Al final del capítulo, la hoja de Røkia está en su garganta y él dice, por primera vez, 'sí'.<br><br>Desde lo alto de los escalones del salón, Varg observa el patio lleno de Juramentados entrenando. Nota a Einar aún cojeando, a Glornir sparring con un guerrero de piel oscura y trenza negra como azabache —único así entre todos los presentes— que le resulta familiar sin que sepa por qué, y a una mujer de cabello plateado con dos sabuesos. Vol no está en ninguna parte."
  },
  {
    chapter: 12,
    title: "Capítulo 12 — Orka",
    summary: "El capítulo arranca justo donde terminó el Althing: el holmganga entre Virk y Guðvarr está a punto de comenzar. Mientras los drengrs marcan el cuadrado con varas de avellano, Orka le explica a Breca las reglas del duelo —un momento de worldbuilding natural que revela cómo funciona la justicia en Vigríð.<br><br>El combate en sí es una lección de experiencia vs. entrenamiento. Guðvarr es joven, lleva brynja, tiene una espada fina y técnica sólida —pero nunca ha visto sangre real. Virk es un pescador con el brazo lesionado y un hacha de carpintero, pero ha peleado de verdad. Virk absorbe los golpes, lo deja agotarse y cuando Guðvarr cae desequilibrado le hunde el hacha en el hombro, seccionándole los músculos. Guðvarr se rinde. Virk gana.<br><br>Entonces Guðvarr, tirado en el suelo, lo insulta. Y Virk alza el hacha para matarlo —violando las reglas del duelo.<br><br>Lo que pasa a continuación es el corazón del capítulo: la thrall-guerrera de Sigrún se lanza sobre Virk antes de que Orka pueda llegar, lo apuñala con sus dos seaxes en frenésí total, y luego le muerde la cara. Los ojos se le vuelven ambarinos, los dientes se le agudizan. Thorkel la patea con tal fuerza que vuela varios metros —y al mismo tiempo recibe un corte de seax. Se para frente a ella y dice en voz alta: <em>«El hombre está muerto; tu tarea está hecha, Ulfrir-kin.»</em><br><br>Sigrún usa Galdur para doblegarla (<em>Brenna, sársauki</em> — arde, dolor), el collar la hace retorcerse hasta que se arrastra a los pies de la jarl. Sigrún declara que Virk rompió las reglas y que la justicia está hecha. Mord y Lif, los hijos de Virk, piden justicia y no la obtienen. El capítulo cierra mientras Orka, Thorkel, Breca y los dos hijos cargan el cuerpo. Al girarse, Orka ve a la thrall sentada en el suelo —mirándolos fijamente, lamiéndose la sangre de Virk del seax.<br><br><strong>Revelaciones clave:</strong> Thorkel nombra a la thrall como «Ulfrir-kin» —sangre del dios-lobo— sin titubear, lo que implica que conoce este mundo mejor de lo que aparenta. Sigrún claramente no controla del todo a su thrall: incluso bajo el dolor del collar, la criatura desafía antes de ceder. Mord y Lif se van con un cuerpo y sin justicia, convirtiéndose en una mecha encendida."
  }
];
